export interface DecorStyle {
  id: string;
  name: string;
  chineseName: string;
  whyPopular: string;
  features: string;
  palette: { background: string; wall: string; floor: string; accent: string; platform: string };
  specialistBrief: string;
  workerActions: string[];
  samplePhotoSearchUrl: string;
}

export const DECOR_STYLES: DecorStyle[] = [
  { id: "japanese-muji", name: "Japanese / Muji", chineseName: "日系 / 無印風", whyPopular: "Makes small flats feel clean, warm, and uncluttered.", features: "Light wood, white walls, simple storage, soft lighting.", palette: { background: "#f3f0e8", wall: "#f8f5ec", floor: "#d8c09c", accent: "#9d8767", platform: "#cdb58e" }, specialistBrief: "Keep the space calm and modular, with pale timber, off-white walls and low visual clutter.", workerActions: ["Use light wood flooring", "Keep walls warm white", "Use soft beige accents", "Prioritise storage-looking built-ins"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/muji-interior" },
  { id: "japandi", name: "Japandi", chineseName: "日式北歐風", whyPopular: "Feels premium while staying practical for compact flats.", features: "Wood, beige/grey tones, clean lines, calm atmosphere.", palette: { background: "#ebe7df", wall: "#eee9df", floor: "#bba787", accent: "#6f7469", platform: "#b49b78" }, specialistBrief: "Blend Japanese restraint with Scandinavian warmth: natural material, muted contrast, and breathable spacing.", workerActions: ["Use beige-grey walls", "Use mid-tone wood floor", "Add muted sage accents", "Keep furniture low and balanced"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/japandi-interior" },
  { id: "modern-minimalist", name: "Modern Minimalist", chineseName: "現代簡約風", whyPopular: "Works well in compact Hong Kong apartments.", features: "Hidden storage, plain colors, simple furniture.", palette: { background: "#ececec", wall: "#f5f5f2", floor: "#c9c7c0", accent: "#40454a", platform: "#b8b8b2" }, specialistBrief: "Reduce visual noise. Use flat planes, concealed storage and a tight grey-white palette.", workerActions: ["Use neutral floor", "Use crisp light walls", "Use charcoal accents", "Avoid busy contrast"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/minimalist-apartment-interior" },
  { id: "nordic-scandinavian", name: "Nordic / Scandinavian", chineseName: "北歐風", whyPopular: "Bright, cozy, family-friendly.", features: "White base, pale wood, fabric sofa, soft colors.", palette: { background: "#f1f3ef", wall: "#ffffff", floor: "#d9c9ad", accent: "#9db6b3", platform: "#d1bd9b" }, specialistBrief: "Maximise daylight and comfort using white surfaces, pale timber and soft fabric-like accent colours.", workerActions: ["Use white walls", "Use pale wood floors", "Add muted blue-green accents", "Keep room labels/furniture friendly"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/scandinavian-interior" },
  { id: "wabi-sabi", name: "Wabi-sabi", chineseName: "侘寂風", whyPopular: "Popular for boutique/luxury flats.", features: "Natural textures, earthy tones, curved shapes, imperfect finishes.", palette: { background: "#e7dfd2", wall: "#d8ccbb", floor: "#b79b7a", accent: "#7a6a58", platform: "#a88968" }, specialistBrief: "Use earthy texture and quiet imperfection; the 3D view should feel grounded and tactile.", workerActions: ["Use clay-beige walls", "Use earthy wood floor", "Use muted brown accents", "Make platforms look stone/wood"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/wabi-sabi-interior" },
  { id: "cream-style", name: "Cream Style", chineseName: "奶油風", whyPopular: "Very popular on Xiaohongshu / Instagram.", features: "Cream, beige, rounded furniture, soft warm lighting.", palette: { background: "#fbf4e8", wall: "#fff7ec", floor: "#ead7bb", accent: "#d3a77e", platform: "#ecd0ac" }, specialistBrief: "Create a soft, photogenic cream apartment mood with warm light and rounded beige forms.", workerActions: ["Use cream walls", "Use warm beige floors", "Use caramel accents", "Keep contrast gentle"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/cream-interior-design" },
  { id: "modern-luxury", name: "Modern Luxury", chineseName: "現代輕奢風", whyPopular: "Common in new private estates.", features: "Marble-look tiles, metal trim, feature wall, warm lighting.", palette: { background: "#ece8df", wall: "#f2eee7", floor: "#c9c2b8", accent: "#b38a45", platform: "#d0cbc4" }, specialistBrief: "Use quiet luxury: light stone surfaces, warm metallic accent, and hotel-like order.", workerActions: ["Use stone-like floor", "Use warm off-white walls", "Use gold accent tone", "Keep edges crisp"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/luxury-apartment-interior" },
  { id: "industrial", name: "Industrial", chineseName: "工業風", whyPopular: "Popular with younger owners and studios.", features: "Cement texture, black metal, exposed track lights.", palette: { background: "#d9d6ce", wall: "#b9b6ae", floor: "#8f8a82", accent: "#252525", platform: "#77736c" }, specialistBrief: "Use concrete grey, black metal contrast and a studio-like rawness while keeping the plan readable.", workerActions: ["Use cement-grey walls", "Use darker floor", "Use black accents", "Let platforms read as concrete"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/industrial-interior" },
  { id: "smart-home-minimalist", name: "Smart Home Minimalist", chineseName: "智能簡約風", whyPopular: "Good for new flats and tech users.", features: "Hidden wiring, smart lighting, motorized curtains, clean design.", palette: { background: "#eef1f2", wall: "#f8faf9", floor: "#c6ced0", accent: "#4a6f86", platform: "#b8c2c5" }, specialistBrief: "Make the 3D model feel clean and tech-ready, with cool neutrals and subtle blue accents.", workerActions: ["Use cool white walls", "Use grey flooring", "Use blue tech accent", "Keep fixtures visually hidden"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/smart-home-interior" },
  { id: "storage-practical", name: "Storage-focused Practical Style", chineseName: "收納實用風", whyPopular: "Very Hong Kong-specific because space is limited.", features: "Full-height cabinets, platform bed, hidden compartments.", palette: { background: "#f0eee7", wall: "#f7f4eb", floor: "#c7b18f", accent: "#8d7b5f", platform: "#b49468" }, specialistBrief: "Prioritise usable storage and raised platforms; the visual language should signal practical built-ins.", workerActions: ["Use warm cabinetry tones", "Emphasise platforms", "Use calm walls", "Prefer storage-friendly furnishing"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/small-apartment-storage" },
  { id: "korean-minimal", name: "Korean Minimal", chineseName: "韓系簡約風", whyPopular: "Softer and warmer than modern minimalist.", features: "Cream/white base, rounded edges, low furniture.", palette: { background: "#f8f1e8", wall: "#fffaf1", floor: "#e3ceb2", accent: "#c89f83", platform: "#e5c4a2" }, specialistBrief: "Use soft cream tones, low contrast and gentle rounded furniture cues.", workerActions: ["Use creamy walls", "Use light warm floor", "Use peach-beige accent", "Keep the scene soft"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/korean-minimal-interior" },
  { id: "luxury-hotel", name: "Luxury Hotel Style", chineseName: "酒店風", whyPopular: "Popular for premium flats and master bedrooms.", features: "Dark wood, stone texture, indirect lighting, built-in panels.", palette: { background: "#ddd6cc", wall: "#cfc4b5", floor: "#6e5540", accent: "#d0a45f", platform: "#80634a" }, specialistBrief: "Make the space feel like a compact suite: darker timber, stone warmth and metallic accent.", workerActions: ["Use dark wood floor", "Use warm stone walls", "Use gold accent", "Make the layout feel hotel-like"], samplePhotoSearchUrl: "https://unsplash.com/s/photos/hotel-style-bedroom-interior" },
];

export function decorStyleById(id?: string) {
  return DECOR_STYLES.find((style) => style.id === id) ?? DECOR_STYLES[0];
}
